name: Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run semantic-release
        if: github.repository == 'sheny1xuan/casbin-cpp' && github.event_name == 'push'
        run: |
          export PATH="$(yarn global bin):$PATH"
          yarn global add semantic-release
          semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: UpdateCmake
        if: github.repository == 'casbin/casbin-cpp' && github.event_name == 'push'
        run: |
          LatestTAG=`git describe --tags`
          cmake_version_updated="    VERSION ${LatestTAG:1}"
          sed -i "/[[:space:]]VERSION/c\\${cmake_version_updated}" CMakeLists.txt